### PR TITLE
Update to Angular 10

### PR DESCRIPTION
**Pull request by AndreyBespamyatnov**
I updated the project to support the latest version of angular
Also, I fixed tests

### CODE REVIEW

**Comment by lula** [comment]
@AndreyBespamyatnov thanks again for your help!

**Comment by AndreyBespamyatnov** [comment]
You are welcome, hope we will have a new version soon)

**Comment by llulani** [comment]
I'm doing that right now :)

**Comment by lula** [comment]
There you go! 0.7.0 is out! (FYI llulani it's always me but I constantly make a mess with my work account eheh)

**Pull request merged**
